spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "${FRONTEND_ORIGIN:http://localhost:5273}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
      routes:
        - id: products-route
          uri: ${CART_SERVICE_URL:http://localhost:8091}
          predicates:
            - Path=/api/products,/api/products/**
          filters:
            - StripPrefix=1

        - id: carts-route
          uri: ${CART_SERVICE_URL:http://localhost:8091}
          predicates:
            - Path=/api/carts,/api/carts/**
          filters:
            - StripPrefix=1

server:
  port: ${SERVER_PORT:8090}

management:
  endpoints:
    web:
      exposure:
        include: health,info
