spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/minicart
    username: minicart
    password: minicart
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
